<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net472;net10.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<SignAssembly>true</SignAssembly>
		<AssemblyOriginatorKeyFile>..\Flank.SsmsExtension\Key.snk</AssemblyOriginatorKeyFile>
	</PropertyGroup>
	<ItemGroup>
		<EmbeddedResource Include="template.xlsx" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net472'">
		<Reference Include="System.IO.Compression" />
		<Reference Include="System.IO.Compression.FileSystem" />
	</ItemGroup>

</Project>
